name: iOS Archive
on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Xcode build (archive)
        run: |
          xcodebuild -project ios-native/MyTaskList.xcodeproj -scheme PetProgress -configuration Release -sdk iphoneos -archivePath $PWD/build/PetProgress.xcarchive archive
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-archive
          path: build/PetProgress.xcarchive
